version: '3'

services:
  witch:
    container_name: witch
    build: .
    environment:
      HUE_USER: YOUR_TOKEN
      HUE_LIGHTS: 1 2 3
    volumes:
      - ./public:/public

  caddy:
    container_name: caddy
    image: caddy
    ports:
      - 80:80
      - 443:443
    command: ["caddy", "reverse-proxy", "--from", "witchonstephendrive.com", "--to", "witch:8080"]
    depends_on:
        - witch
    logging:
      driver: none