version: '3'

services:
  redis:
    container_name: redis
    network_mode: host
    restart: always
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro

  witch-server:
    container_name: witch-server
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:witch
    command: server
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis

  witch-client:
    container_name: witch-client
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:witch
    command: client
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis

  caddy:
    container_name: caddy
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
        - witch-server

  assistant-relay:
    container_name: assistant-relay
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:assistant-relay
    volumes:
      - ~/config.json:/bin/config.json # To be configured
      - /etc/localtime:/etc/localtime:ro

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
