version: '3'

services:
  witch:
    container_name: witch
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:witch
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  caddy:
    container_name: caddy
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
        - witch

  assistant-relay:
    container_name: assistant-relay
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:assistant-relay
    volumes:
      - ~/config.json:/bin/config.json # To be configured
      - /etc/localtime:/etc/localtime:ro

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
