version: '3'

services:
  witch:
    container_name: witch
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:witch
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  caddy:
    container_name: caddy
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
        - witch

 homeassistant:
    container_name: homeassistant
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:home-assistant
    privileged: true
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
   env_file: .env
   depends_on:
     - witch

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

  prometheus:
    container_name: prometheus
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.time=30d
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prometheus_data:/prometheus
    depends_on:
      - witch

  grafana:
    container_name: grafana
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  home_assistant_data:
  prometheus_data:
  grafana_data:
