version: '3'

services:
  witch:
    container_name: witch
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:witch
    environment:
      ASSISTANT_DEVICE: YOUR_DEVICE_NAME_OR_IP  # To be configured
      HUE_USER: YOUR_TOKEN  # To be configured
      HUE_LIGHTS: 1,2,3  # To be configured

  caddy:
    container_name: caddy
    network_mode: host
    restart: always
    image: caddy
    ports:
      - 80:80
      - 443:443
    command: ["caddy", "reverse-proxy", "--from", "witchonstephendrive.com", "--to", "127.0.0.1:8080"]
    depends_on:
        - witch

  assistant-relay:
    container_name: assistant-relay
    network_mode: host
    restart: always
    image: circa10a/witchonstephendrive.com:assistant-relay
    volumes:
      - ~/config.json:/bin/config.json

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 3600
