{
 "title": "witchonstephendrive.com",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Color Changes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/color/.*\"})"
    }
   ]
  },
  {
   "title": "All Color Changes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/color/\\\\w.*\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Total Sound Plays",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/sound/.*\"})"
    }
   ]
  },
  {
   "title": "All Sound Changes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/sound/\\\\w.*\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Color responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/color/.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Sound responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "count(echo_requests_total{host=\"witchonstephendrive.com\",method=\"POST\",url=~\"/sound/.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Response times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (url)(rate(echo_request_duration_seconds_sum[$__range])) / sum by (url)(rate(echo_request_duration_seconds_count[$__range]))",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}