FROM grafana/grafana
RUN mkdir -p /etc/grafana/provisioning/datasources/ && \
    mkdir -p /etc/grafana/provisioning/dashboards/
# Dashboards provisioning config
COPY ../monitoring/grafana/dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
# Copy dashboards
COPY ../monitoring/grafana/dashboards/*.json /etc/grafana/provisioning/dashboards/
# Datasources provisioning config
COPY ../monitoring/grafana/datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
# Grafana config
COPY ../monitoring/grafana/grafana.ini /etc/grafana/grafana.ini