name: build-docker-images

on:
  workflow_run:
    workflows:
      - test
    branches:
      - main
    types:
       - completed

env:
  PLATFORMS: linux/arm/v7,linux/amd64,linux/arm64

jobs:
  docker-build-witch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:witch
  docker-build-caddy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile.caddy
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:caddy
  docker-build-home-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile.home-assistant
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:home-assistant
  docker-build-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile.prometheus
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:prometheus
  docker-build-grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile.grafana
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:grafana

