name: build-docker-images

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
    types:
       - completed

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push witch
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:witch
      - name: Build and push caddy
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile.caddy
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:caddy
      - name: Build and push assistant-relay
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile.assistant-relay
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:assistant-relay
      - name: Build and push prometheus
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile.prometheus
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:prometheus
      - name: Build and push grafana
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/Dockerfile.grafana
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:grafana
